'use strict';

// ============================================================
// TOKEN FRAMES — bake a Tokenizer 2 frame onto this module's
// actors the first time one is dropped on the canvas.
// ============================================================
//
// Tokenizer 2 is optional. Without it this file does nothing at
// all, and the module's own pre-baked ring art is used as before.
//
// WHY A DROP HOOK AT ALL
//   Tokenizer's own automation is the "Auto Token" dialog on a
//   compendium — a batch pass the GM runs by hand. That writes to
//   the pack, and this module's packs are regenerated by `npm run
//   build`, so those edits would not survive an update. Tokenizing
//   on drop writes to the *world* actor instead, which nothing here
//   overwrites.
//
// WHY forceBakedRing
//   tokenize() picks dynamic-ring output when the prototype token
//   has ring.enabled — and every actor in this module does, because
//   scripts/generate-tokens.mjs bakes ring subjects. Left alone it
//   would hand back the same ring art that is already shipping and
//   no frame would appear. forceBakedRing composites the frame into
//   the image, which is the thing being asked for, so the dynamic
//   ring is then turned off on the token to avoid drawing two.
//
// The first drop of a given actor shows the shipped art for a moment
// while the composite runs; every later drop is instant, because the
// work lands on the actor.
// ============================================================

const MODULE_ID = 'mass-effect-sf2e-conversion';
const TOKENIZER_ID = 'tokenizer-2';
const S_AUTO_FRAME = 'autoFrameTokens';
const S_FRAME_SRC = 'tokenFrameSrc';

/** One in-flight tokenize per actor: a crate of six mechs is one composite. */
const inFlight = new Map();

/** @returns {object|null} Tokenizer 2's API, or null when it is not available. */
function tokenizer() {
  const mod = game.modules.get(TOKENIZER_ID);
  if (!mod?.active) return null;
  return mod.api ?? globalThis.Tokenizer2 ?? null;
}

/** Actors this module ships: their art lives under the module's own folder. */
function isModuleActor(actor) {
  const source = actor?._stats?.compendiumSource ?? '';
  if (source.includes(`.${MODULE_ID}.`)) return true;
  const paths = `${actor?.prototypeToken?.texture?.src ?? ''}|${actor?.img ?? ''}`;
  return paths.includes(`modules/${MODULE_ID}/`);
}

/**
 * Tokenizer's own test, kept in step deliberately: a layer stack flag, or
 * "tokenizer" somewhere in the paths.
 */
function isTokenized(actor) {
  if (actor.getFlag(TOKENIZER_ID, 'layerStack')) return true;
  const paths = `${actor.prototypeToken?.texture?.src ?? ''}|${actor.img ?? ''}`;
  return paths.toLowerCase().includes('tokenizer');
}

/**
 * Composite a frame onto one actor and return its new token image.
 * @returns {Promise<string|null>} the new texture path, or null if nothing happened
 */
async function frameActor(actor) {
  const api = tokenizer();
  if (!api?.tokenize) return null;
  if (inFlight.has(actor.id)) return inFlight.get(actor.id);

  const frameSrc = game.settings.get(MODULE_ID, S_FRAME_SRC) || null;
  const work = (async () => {
    await api.tokenize(actor, {
      frameSrc,                 // null lets Tokenizer pick by disposition
      forceBakedRing: true,     // see the header: the shipped ring art wins otherwise
      wildcardMode: 'keep',     // never disturb an actor set up with wildcard art
      updateActor: true,
    });
    return actor.prototypeToken?.texture?.src ?? null;
  })();

  inFlight.set(actor.id, work);
  try {
    return await work;
  } finally {
    inFlight.delete(actor.id);
  }
}

/** Frame the actor behind a freshly placed token, then repoint the token at it. */
async function onCreateToken(document, options, userId) {
  if (game.user.id !== userId || !game.user.isGM) return;
  if (!game.settings.get(MODULE_ID, S_AUTO_FRAME)) return;
  if (!tokenizer()) return;

  // Selections and art live on the world actor; an unlinked token's own actor is
  // a synthetic delta that carries neither.
  const actor = document.baseActor ?? document.actor;
  if (!actor || !isModuleActor(actor) || isTokenized(actor)) return;

  try {
    const src = await frameActor(actor);
    if (!src) return;
    // A baked frame and a dynamic ring would draw two rings around the art.
    await document.update({ 'texture.src': src, 'ring.enabled': false });
    console.log(`${MODULE_ID} | framed "${actor.name}" with Tokenizer 2`);
  } catch (err) {
    console.error(`${MODULE_ID} | Tokenizer 2 could not frame "${actor.name}"`, err);
    ui.notifications.warn(`ME Tokens | Tokenizer 2 could not frame "${actor.name}". See the console.`);
  }
}

/**
 * Frame every actor of this module's that is already in the world.
 * Exposed on the module API for a one-off pass: MassEffect.frameTokens.all().
 */
async function frameAll({ untokenizedOnly = true } = {}) {
  const api = tokenizer();
  if (!api?.tokenizeBatch) {
    ui.notifications.warn('ME Tokens | Tokenizer 2 is not available.');
    return 0;
  }
  const actors = game.actors.filter((a) => isModuleActor(a) && (!untokenizedOnly || !isTokenized(a)));
  if (!actors.length) return 0;

  const frameSrc = game.settings.get(MODULE_ID, S_FRAME_SRC) || null;
  await api.tokenizeBatch(actors, { frameSrc, forceBakedRing: true, wildcardMode: 'keep' });
  ui.notifications.info(`ME Tokens | Framed ${actors.length} actor(s) with Tokenizer 2.`);
  return actors.length;
}

Hooks.once('init', () => {
  game.settings.register(MODULE_ID, S_AUTO_FRAME, {
    name: 'Frame Tokens With Tokenizer 2',
    hint: 'The first time one of this module’s actors is dropped on the canvas, composite a frame onto its token art with Tokenizer 2. The result is saved to the world actor, so later drops are instant and a module update will not undo it. Needs Tokenizer 2 installed and active.',
    scope: 'world',
    config: true,
    type: Boolean,
    default: false,
  });

  game.settings.register(MODULE_ID, S_FRAME_SRC, {
    name: 'Token Frame Image',
    hint: 'The frame to composite. Leave blank to let Tokenizer 2 choose by token disposition, which gives hostiles, neutrals and allies their own frames.',
    scope: 'world',
    config: true,
    type: String,
    default: '',
    filePicker: 'image',
  });
});

Hooks.once('ready', () => {
  if (!game.user.isGM) return;

  const api = (game.modules.get(MODULE_ID).api ??= {});
  api.frameTokens = { one: frameActor, all: frameAll, available: () => !!tokenizer() };

  // Always listen; the handler re-checks the setting, so turning it on mid-session
  // works without a reload.
  Hooks.on('createToken', onCreateToken);

  const on = game.settings.get(MODULE_ID, S_AUTO_FRAME);
  const version = game.modules.get(TOKENIZER_ID)?.version;
  if (on && !tokenizer()) {
    console.warn(`${MODULE_ID} | token framing is on, but Tokenizer 2 is not active`);
  } else if (on) {
    console.log(`${MODULE_ID} | token framing armed (Tokenizer 2 ${version})`);
  }
});
