'use strict';

// ============================================================
// TOKEN FRAMES — bake a Tokenizer 2 frame onto this module's
// actors the first time one is dropped on the canvas.
// ============================================================
//
// Tokenizer 2 is optional. Without it this file does nothing at
// all, and the module's own pre-baked ring art is used as before.
//
// WHY A DROP HOOK AT ALL
//   Tokenizer's own automation is the "Auto Token" dialog on a
//   compendium — a batch pass the GM runs by hand. That writes to
//   the pack, and this module's packs are regenerated by `npm run
//   build`, so those edits would not survive an update. Tokenizing
//   on drop writes to the *world* actor instead, which nothing here
//   overwrites.
//
// WHY forceBakedRing
//   tokenize() picks dynamic-ring output when the prototype token
//   has ring.enabled — and every actor in this module does, because
//   scripts/generate-tokens.mjs bakes ring subjects. Left alone it
//   would hand back the same ring art that is already shipping and
//   no frame would appear. forceBakedRing composites the frame into
//   the image, which is the thing being asked for, so the dynamic
//   ring is then turned off on the token to avoid drawing two.
//
// The first drop of a given actor shows the shipped art for a moment
// while the composite runs; every later drop is instant, because the
// work lands on the actor.
// ============================================================

const MODULE_ID = 'mass-effect-sf2e-conversion';
const TOKENIZER_ID = 'tokenizer-2';
const S_AUTO_FRAME = 'autoFrameTokens';
const S_CONFIG = 'tokenizeConfig';

/** One in-flight tokenize per actor: a crate of six mechs is one composite. */
const inFlight = new Map();

/** @returns {object|null} Tokenizer 2's API, or null when it is not available. */
function tokenizer() {
  const mod = game.modules.get(TOKENIZER_ID);
  if (!mod?.active) return null;
  return mod.api ?? globalThis.Tokenizer2 ?? null;
}

/** Actors this module ships: their art lives under the module's own folder. */
function isModuleActor(actor) {
  const source = actor?._stats?.compendiumSource ?? '';
  if (source.includes(`.${MODULE_ID}.`)) return true;
  const paths = `${actor?.prototypeToken?.texture?.src ?? ''}|${actor?.img ?? ''}`;
  return paths.includes(`modules/${MODULE_ID}/`);
}

/**
 * Tokenizer's own test, kept in step deliberately: a layer stack flag, or
 * "tokenizer" somewhere in the paths.
 */
function isTokenized(actor) {
  if (actor.getFlag(TOKENIZER_ID, 'layerStack')) return true;
  const paths = `${actor.prototypeToken?.texture?.src ?? ''}|${actor.img ?? ''}`;
  return paths.toLowerCase().includes('tokenizer');
}

/**
 * Composite a frame onto one actor and return its new token image.
 * @returns {Promise<string|null>} the new texture path, or null if nothing happened
 */
async function frameActor(actor) {
  const api = tokenizer();
  if (!api?.tokenize) return null;
  if (inFlight.has(actor.id)) return inFlight.get(actor.id);

  const work = (async () => {
    await api.tokenize(actor, tokenizeOptions());
    return actor.prototypeToken?.texture?.src ?? null;
  })();

  inFlight.set(actor.id, work);
  try {
    return await work;
  } finally {
    inFlight.delete(actor.id);
  }
}

/**
 * What to hand tokenize().
 *
 * Whatever the GM chose in Tokenizer's own config dialog, with two things
 * pinned: never disturb an actor set up with wildcard art, and bake the frame
 * into the image unless they deliberately asked for a dynamic ring — the
 * shipped art is already ring-ready, so leaving that to chance means no frame.
 */
function tokenizeOptions() {
  const chosen = game.settings.get(MODULE_ID, S_CONFIG) ?? {};
  const baked = chosen.forceDynamicRing ? {} : { forceBakedRing: true };
  return { ...chosen, ...baked, wildcardMode: 'keep', updateActor: true };
}

/** A short description of the current choice, for the settings menu. */
function frameLabel() {
  const chosen = game.settings.get(MODULE_ID, S_CONFIG) ?? {};
  if (chosen.forceDynamicRing) return 'Foundry dynamic ring';
  if (!chosen.frameSrc) return "Tokenizer's default, by disposition";
  return chosen.frameSrc.split('/').pop();
}

/**
 * Pick the frame in Tokenizer's own dialog: its frame browser, its mask modes,
 * and a live preview on one of this module's own actors. Whatever it returns is
 * stored whole and spread back into tokenize().
 */
async function chooseFrame() {
  const api = tokenizer();
  if (!api?.promptConfig) {
    ui.notifications.warn('ME Tokens | Tokenizer 2 is not available, so there is no frame browser to open.');
    return null;
  }
  const config = await api.promptConfig(game.settings.get(MODULE_ID, S_CONFIG) ?? {});
  if (!config) return null;   // cancelled
  await game.settings.set(MODULE_ID, S_CONFIG, config);
  ui.notifications.info(`ME Tokens | Frame set to ${frameLabel()}.`);
  return config;
}

/** Frame the actor behind a freshly placed token, then repoint the token at it. */
async function onCreateToken(document, options, userId) {
  if (game.user.id !== userId || !game.user.isGM) return;
  if (!game.settings.get(MODULE_ID, S_AUTO_FRAME)) return;
  if (!tokenizer()) return;

  // Selections and art live on the world actor; an unlinked token's own actor is
  // a synthetic delta that carries neither.
  const actor = document.baseActor ?? document.actor;
  if (!actor || !isModuleActor(actor) || isTokenized(actor)) return;

  try {
    const src = await frameActor(actor);
    if (!src) return;
    // A baked frame and a dynamic ring would draw two rings around the art, so the
    // ring goes — unless the dynamic ring is what was asked for.
    const dynamic = !!(game.settings.get(MODULE_ID, S_CONFIG) ?? {}).forceDynamicRing;
    await document.update({ 'texture.src': src, 'ring.enabled': dynamic });
    console.log(`${MODULE_ID} | framed "${actor.name}" with Tokenizer 2`);
  } catch (err) {
    console.error(`${MODULE_ID} | Tokenizer 2 could not frame "${actor.name}"`, err);
    ui.notifications.warn(`ME Tokens | Tokenizer 2 could not frame "${actor.name}". See the console.`);
  }
}

/**
 * Frame every actor of this module's that is already in the world.
 * Exposed on the module API for a one-off pass: MassEffect.frameTokens.all().
 */
async function frameAll({ untokenizedOnly = true } = {}) {
  const api = tokenizer();
  if (!api?.tokenizeBatch) {
    ui.notifications.warn('ME Tokens | Tokenizer 2 is not available.');
    return 0;
  }
  const actors = game.actors.filter((a) => isModuleActor(a) && (!untokenizedOnly || !isTokenized(a)));
  if (!actors.length) return 0;

  await api.tokenizeBatch(actors, tokenizeOptions());
  ui.notifications.info(`ME Tokens | Framed ${actors.length} actor(s) with Tokenizer 2.`);
  return actors.length;
}

Hooks.once('init', () => {
  game.settings.register(MODULE_ID, S_AUTO_FRAME, {
    name: 'Frame Tokens With Tokenizer 2',
    hint: 'The first time one of this module’s actors is dropped on the canvas, composite a frame onto its token art with Tokenizer 2. The result is saved to the world actor, so later drops are instant and a module update will not undo it. Needs Tokenizer 2 installed and active.',
    scope: 'world',
    config: true,
    type: Boolean,
    default: false,
  });

  // Tokenizer's own dialog returns frame, mask, fit and ring mode together, so
  // the whole object is what gets stored.
  game.settings.register(MODULE_ID, S_CONFIG, {
    scope: 'world',
    config: false,
    type: Object,
    default: {},
  });

  game.settings.registerMenu(MODULE_ID, 'tokenFramePicker', {
    name: 'Token Frame',
    label: 'Choose Frame…',
    hint: "Opens Tokenizer 2's frame browser, with its mask modes and a live preview. Leave it unset to let Tokenizer pick by token disposition, so hostiles, neutrals and allies differ.",
    icon: 'fas fa-circle-notch',
    type: FramePickerMenu,
    restricted: true,
  });
});

/**
 * A settings-menu entry that is really just a button: Foundry renders the
 * registered type, and this one opens Tokenizer's dialog instead of a window of
 * its own.
 */
class FramePickerMenu extends foundry.applications.api.ApplicationV2 {
  static DEFAULT_OPTIONS = { id: 'me-token-frame-picker' };

  async render() {
    await chooseFrame();
    return this;
  }
}

Hooks.once('ready', () => {
  if (!game.user.isGM) return;

  const api = (game.modules.get(MODULE_ID).api ??= {});
  api.frameTokens = { one: frameActor, all: frameAll, chooseFrame, available: () => !!tokenizer() };

  // Always listen; the handler re-checks the setting, so turning it on mid-session
  // works without a reload.
  Hooks.on('createToken', onCreateToken);

  const on = game.settings.get(MODULE_ID, S_AUTO_FRAME);
  const version = game.modules.get(TOKENIZER_ID)?.version;
  if (on && !tokenizer()) {
    console.warn(`${MODULE_ID} | token framing is on, but Tokenizer 2 is not active`);
  } else if (on) {
    console.log(`${MODULE_ID} | token framing armed (Tokenizer 2 ${version})`);
  }
});
